### ISSUE TITLE
Summing Linear Demands (two individuals) - price at zero causes handle to disappear

### ISSUE THREAD

**Issue by dharmatech** [cmakler/kgjs#44]
Hello!

On this example:

https://www.econgraphs.org/graphs/micro/equilibrium/partial_equilibrium/summing_two_individuals_linear_demands

If you drag the price for consumer 1 to zero and release the mouse, it seems there's no way to readjust the price without reloading the page.

Perhaps there's a way to keep the handle enabled even if the price is at zero?

**Comment by cmakler** [comment]
Hi! I very rarely look here, so I completely missed this.

That's definitely a bug. I'll look into why it's happening...

Best,

Chris

**Comment by cmakler** [comment]
fixed! nifty little bug... when you dragged the handle below the axis, it was calculating the slope as if it were an upward-sloping demand curve, which caused it to disappear! Added a lower bound to the drag. Thanks for pointing this out!
